services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.8
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /etc/nginx/conf.d
    networks:
      - proxy-tier
    labels:
      - "com.github.nginx-proxy.nginx"

  letsencrypt:
    image: nginxproxy/acme-companion:2.4
    container_name: nginx-proxy-acme
    restart: always
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /etc/nginx/conf.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - proxy-tier

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme:

networks:
  proxy-tier:
    driver: bridge